# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               IDEEAS Lab
tagline:             'Improving Decisions in Engineering Education Agents and Systems'
description:         'Home of the IDEEAS Lab'
url:                 http://ideeaslab.github.io
baseurl:             ''
# The following line is required for Jekyll >=3 support
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5

# About/contact
author:
  name:              IDEEAS Lab Name
  url:               http://ideeaslab.com
  email:             akatz4@vt.edu

# Custom vars
version:             Lanyon
